
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTERROGACION = 11;
  public static final int PUNTO = 7;
  public static final int PUNTOYCOMA = 12;
  public static final int DOSPUNTOS = 5;
  public static final int CADENA = 15;
  public static final int OR = 8;
  public static final int CONJUNTOSIGNO = 19;
  public static final int LLAVERIGHT = 3;
  public static final int FLECHA = 6;
  public static final int ID = 14;
  public static final int POR = 9;
  public static final int SEPARADOR = 13;
  public static final int EOF = 0;
  public static final int CONJ = 4;
  public static final int error = 1;
  public static final int CONJUNTOMIN = 17;
  public static final int LLAVELEFT = 2;
  public static final int CONJUNTOMAY = 16;
  public static final int CONJUNTODIGITO = 18;
  public static final int MAS = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAVELEFT",
  "LLAVERIGHT",
  "CONJ",
  "DOSPUNTOS",
  "FLECHA",
  "PUNTO",
  "OR",
  "POR",
  "MAS",
  "INTERROGACION",
  "PUNTOYCOMA",
  "SEPARADOR",
  "ID",
  "CADENA",
  "CONJUNTOMAY",
  "CONJUNTOMIN",
  "CONJUNTODIGITO",
  "CONJUNTOSIGNO"
  };
}

